telos:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  


  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: corpus_to_right_front_thigh
    pid: {p: 1.0, i: 0.01, d: 10.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: thigh_to_right_front_feet
    pid: {p: 1.0, i: 0.01, d: 10.0}


  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: corpus_to_left_front_thigh
    pid: {p: 1.0, i: 0.01, d: 10.0}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: thigh_to_left_front_feet
    pid: {p: 1.0, i: 0.01, d: 10.0}


  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: corpus_to_right_back_thigh
    pid: {p: 1.0, i: 0.01, d: 10.0}

  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: thigh_to_right_back_feet
    pid: {p: 1.0, i: 0.01, d: 10.0}


  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: corpus_to_left_back_thigh
    pid: {p: 1.0, i: 0.01, d: 10.0}

  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: thigh_to_left_back_feet
    pid: {p: 1.0, i: 0.01, d: 10.0}